[package]
name = "local"
version = "0.1.0"
authors = ["emilyaherbert <emilyherbert@cs.umass.edu>"]
edition = "2018"

[dependencies]
hyper = "0.12"
futures = "0.1" 
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.7"