openapi: 3.0.0
info:
  description: |
    API for the log-echo-agent program, which echoes logs that it receives to
    standard out.
  title: log-echo API
  version: 1.0.0
servers:
- url: http://localhost
paths:
  /log:
    post:
      description: Echo a message to the log
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                text:
                  example: This is an example log message
                  type: string
                target:
                  example: controller
                  type: string
                level:
                  example: INFO
                  type: string
              type: object
        required: true
      responses:
        "200":
          description: OK
components:
  requestBodies:
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  schemas:
    inline_object:
      properties:
        text:
          example: This is an example log message
          type: string
        target:
          example: controller
          type: string
        level:
          example: INFO
          type: string
      type: object

