trigger:
- master

jobs:
- job: build
  displayName: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;isOutput=true]$HOME/.cargo/bin:$PATH"
      cargo version
    name: install_rust
    displayName: Install rust
  - task: CacheBeta@0
    inputs:
      key: version5 | $(Agent.OS)
      path: /home/vsts/.cargo, /home/vsts/rust/compiler/target
    displayName: Cache Cargo and Yarn packages
  - script: |
      cd rust/compiler
      ls -l $HOME/.cargo/bin
      chmod a+x $HOME/.cargo/bin/*
      set -x
      set -e
      find $HOME/.cargo/registry/cache -maxdepth 2
      PATH=$HOME/.cargo/bin:$PATH cargo build
      cd ../../javascript/containerless
      yarn install
      yarn run build
      cd ../js-transform
      yarn install
      yarn run build
      ls /home/vsts/rust/compiler/target

- job: test_javascript
  displayName: Tests (JavaScript)
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: build
  steps:
  - script: |
      cd javascript/containerless
      yarn run test

- job: test_rust
  displayName: Tests (Rust)
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: build
  variables:
    PATH: $[dependencies.build.outputs['install_rust.PATH']]
  steps:
  - task: CacheBeta@0
    inputs:
      key: version5 | $(Agent.OS)
      path: /home/vsts/.cargo, /home/vsts/rust/compiler/target
    displayName: Cache Cargo and Yarn packages
  - script: |
      ls -l $HOME/.cargo/bin
      chmod a+x $HOME/.cargo/bin/*
      cd rust/compiler
      cargo test

