# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
variables:
  CARGO_CACHE_FOLDER: $(Pipeline.Workspace)/.cargo
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.config/yarn
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: Install Node and Yarn
- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    echo "##vso[task.setvariable variable=PATH;isOutput=true]$HOME/.cargo/bin:$PATH"
    cargo version
  name: install_rust
  displayName: Install rust
- task: CacheBeta@0
  inputs:
    key: $(Agent.OS)
    path: /home/vsts/.cargo
  displayName: Cache Cargo and Yarn packages
- script: |
    which cargo
    cd javascript/containerless
    yarn install
    yarn run build
    cd ../js-transform
    yarn install
    yarn run build
    cd ../../rust/compiler
    cargo build
  displayName: Build
- script: |
    cd javascript/containerless
    yarn run test
- script: |
    cd rust/compiler
    cargo test

