# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


jobs:
- job: deps
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
- job: build
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: deps
  steps:
  - task: CacheBeta@0
    inputs:
      key: cargo | $(Agent.OS)
      path: $HOME/.cargo, $HOME/.config/yarn
    displayName: Cache Cargo and Yarn packages
  - script: |
      cd javascript/containerless
      yarn install
      yarn run build
      cd ../js-transform
      yarn install
      yarn run build
      cd ../../rust/compiler
      cargo build

- job: test_containerless
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: build
  steps:
  - script: |
      cd javascript/containerless
      yarn run test
- job: test_compiler
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: build
  steps:
  - script: |
      cd rust/compiler
      cargo test

