trigger:
- master
variables:
  CARGO_CACHE_FOLDER: $(Pipeline.Workspace)/.cargo
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.config/yarn

jobs:
- job: deps
  displayName: Install build tools
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;isOutput=true]$HOME/.cargo/bin:$PATH"
      cargo version
    name: install_rust
    displayName: Install rust
- job: build
  pool:
    vmImage: 'ubuntu-latest'
  displayName: Build
  dependsOn: deps
  variables:
    PATH: $[dependencies.deps.outputs['install_rust.PATH']]
  steps:
  - task: CacheBeta@0
    inputs:
      key: version2 | $(Agent.OS)
      path: /home/vsts/.cargo/registry
    displayName: Cache Cargo and Yarn packages
  - script: |
      which cargo
      cd javascript/containerless
      yarn install
      yarn run build
      cd ../js-transform
      yarn install
      yarn run build
      cd ../../rust/compiler
      cargo build
  - publish: $(Pipeline.Workspace)/.cargo
    artifact: .cargo

- job: test_javascript
  displayName: Tests (JavaScript)
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: build
  steps:
  - script: |
      cd javascript/containerless
      yarn run test
- job: test_rust
  displayName: Tests (Rust)
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: build
  steps:
  - download: current
    artifact: .cargo
  - script: |
      cd rust/compiler
      cargo test

