# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: deps
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
- job: build
  dependsOn: deps
  steps:
  - script: |
      cd javascript/containerless
      yarn install
      yarn run build
      cd ../js-transform
      yarn install
      yarn run build
      cd ../../rust/compiler
      cargo build
- job: test-containerless
  dependsOn: build
  steps:
  - script: |
    cd javascript/containerless
    yarn run test
- job: test-compiler
  dependsOn: build
  steps:
  - script: |
    cd rust/compiler
    yarn run test
