[package]
name = "decontainerization"
version = "0.1.0"
authors = ["Arjun Guha <arjun@cs.umass.edu>"]
edition = "2018"

[dependencies]
syn = "*"
quote = "*"
proc-macro2 = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"