openapi: 3.0.0
info:
  description: |
    API for the log-echo-agent program, which echoes logs that it receives to
    standard out.
  title: log-echo API
  version: 1.0.0
servers:
- url: http://localhost
paths:
  /log:
    post:
      description: Echo a message to the log
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: This is an example log message
                target:
                  type: string
                  example: controller
                level:
                  type: string
                  example: INFO
      responses:
        "200":
          description: OK

