[package]
name = "simple_http_endpoint"
version = "0.1.0"
autobins = false

[dependencies]
lambda_runtime = "^0.1"
serde = "^1"
serde_json = "^1"
serde_derive = "^1"
chrono = "^0.4"

[[bin]]
name = "bootstrap"
path = "src/main.rs"