[package]
name = "trace-runtime"
version = "0.1.0"
authors = [
    "Arjun Guha <arjun@cs.umass.edu>",
    "Emily Herbert <emilyherbert@cs.umass.edu>"
]
edition = "2018"

[dependencies]
hyper = "*"
hyper-tls = "*"
futures = "*"
bumpalo = "*"
tokio = "*"
tokio-core = "*"