[package]
name = "trace-verif"
version = "0.1.0"
authors = ["emilyaherbert <emilyherbert@cs.umass.edu>"]
edition = "2018"

[dependencies]
im-rc = "*"
quote = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
trace-runtime = { path = "../trace-runtime" }