[package]
name = "rust-gen"
version = "0.1.0"
authors = ["emilyaherbert <emilyherbert@cs.umass.edu>"]
edition = "2018"

[dependencies]
trace-verif = { path = "../trace-verif" }
trace-runtime = { path = "../trace-runtime" }