# Namespace for Containerless
apiVersion: v1
kind: Namespace
metadata:
    name: containerless
---
# This ReplicaSet runs the controller. Note that the number of replicates
# must be exactly 1. The controller-agent is not designed to be
# replicated.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: controller
  namespace: containerless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: localhost:32000/controller
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: /ready
            port: 80
        volumeMounts:
          - name: rust-src
            mountPath: "/src"
      volumes:
        - name: rust-src
          hostPath:
            path: $RUST_SRC_PATH

---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: containerless
spec:
  selector:
    app: controller
  ports:
    - name: http
      port: 80
---
# This Deployment runs the dispatcher.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
  namespace: containerless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
      - name: dispatcher
        image: localhost:32000/dispatcher
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: RUST_LOG
            value: error,dispatcher=debug,dispatcher-launcher=info
          - name: Version
            value: V1
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: /readinessProbe/
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcher
  namespace: containerless
spec:
  type: NodePort
  selector:
    app: dispatcher
  ports:
    - name: http
      port: 8080
---
# This ReplicaSet runs function storage. Note that the number of replicates
# must be exactly 1. The function-storage-agent is not designed to be
# replicated.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: storage
  namespace: containerless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: storage
        image: localhost:32000/function-storage
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: storage
            mountPath: "/storage"
      volumes:
        - name: storage
          hostPath:
            path: $EXAMPLES_PATH
---
apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: containerless
spec:
  type: NodePort
  selector:
    app: storage
  ports:
    - name: http
      port: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: containerless-ingress
  namespace: containerless
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
        - path: /storage(/|$)(.*)
          backend:
            serviceName: storage
            servicePort: http
        - path: /dispatcher(/|$)(.*)
          backend:
            serviceName: dispatcher
            servicePort: http
