[package]
name = "fetch-and-store-file"
version = "0.1.0"
autobins = false

[dependencies]
lambda_runtime = "^0.1"
serde = "^1"
serde_json = "^1"
serde_derive = "^1"
log = "^0.4"
simple_logger = "^1"
aws-sdk-rust = "^0.1.42"

[[bin]]
name = "bootstrap"
path = "src/main.rs"
