[package]
name = "decontainerization-trace-runtime"
version = "0.1.0"
authors = ["Arjun Guha <arjun@cs.umass.edu>"]
edition = "2018"

[dependencies]
hyper = "*"
futures = "*"
bumpalo = "*"
tokio = "*"