[package]
name = "go-runtime-http-endpoint"
version = "0.1.0"

[dependencies]
aws_lambda = { git = "https://github.com/srijs/rust-aws-lambda" }
chrono = "^0.4"


[[bin]]
name = "bootstrap"
path = "src/main.rs"