[workspace]
members = [
    "shared2",
    "controller-agent",
    "dispatcher-agent",
    "dispatcher-launcher-agent",
    "function-runner-agent",
    "function-storage-agent",
    "k8s",
    "integration-tests",
]
exclude = [ "compiler", "containerless-scaffold", "invoker" ]