[package]
name = "local"
version = "0.1.0"
authors = ["emilyaherbert <emilyherbert@cs.umass.edu>"]
edition = "2018"

[dependencies]
futures = "*"
hyper = "*"
tokio = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
clap = "*"
rand = "*"
time = "*"