[package]
name = "common"
version = "0.1.0"
authors = ["emilyaherbert <emilyherbert@cs.umass.edu>"]
edition = "2018"

[dependencies]
im-rc = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
