[package]
name = "simple-forecast"
version = "0.1.0"
autobins = false

[dependencies]
lambda_runtime = "^0.1"
serde = "^1"
serde_json = "^1"
serde_derive = "^1"
log = "^0.4"
simple_logger = "^1"
forecast = "^2.0.0"
reqwest = "^0.9.5"

[[bin]]
name = "bootstrap"
path = "src/main.rs"
