[package]
name = "function-storage-agent"
version = "0.1.0"
authors = ["arjun"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "*"
tokio = { version = "*", features = ["macros", "fs"] }
hyper = "*"