# Namespace for Containerless
# This is a template for a Kubernetes configuration that creates static
# resources for Containerless. The template has several variables:
# - $CONTROLLER_IP and $CONTROLLER_PORT are the IP address and port at which the
#   the controller is running, and must be reachable by pods running in
#   Kubernetes.
# - $CONTROLLER_LOG_PATH is the path on the local machine where the controller
#   log appears.
#
# The template creates the following resources:
# - A namespace called "containerless".
# - An endpoint and service, both called "controller", which allow pods in
#   the cluster to communicate with the controller using http://controller:80.
# - A service called "dispatcher" that selects pods with selector
#   "app=dispatcher". The service makes dispatchers available in the cluster
#   at http://dispatcher:8080. (Yes, we use different ports. This is bad, and
#   we should fix it!)
# - A replicaSet and service, both called "storage", that runs the function
#   storage agent. We have a really trivial storage service that does not
#   support replication. However, the replicaSet ensures that it restarts
#   if anything goes wrong. (Is that even desirable?) The service makes
#   function storage available in the cluster at http://storage:8080.
# - An ingress that runs at port 80, and exposes /storage, /dispatcher, and
#   /controller outside the cluster.
# - A pod called controller-logger that echoes the controller's log file to
#   its own output. Thus, even when the controller is running outside of
#   the cluster, its logs are available in the cluster and can be aggregated
#   with all other logs.
# Assumptions:
# - The controller-logger pod must run on the same machine -- so that it can
#   share the file system with the controller.
apiVersion: v1
kind: Namespace
metadata:
    name: containerless
---
apiVersion: v1
kind: Endpoints
metadata:
  name: controller
  namespace: containerless
subsets:
  - addresses:
    - ip: $CONTROLLER_IP
    ports:
    - port: $CONTROLLER_PORT
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: containerless
  labels:
    app: controller
spec:
  ports:
    - name: http
      port: 80
      targetPort: $CONTROLLER_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcher
  namespace: containerless
  labels:
    app: dispatcher
spec:
  type: NodePort
  selector:
    app: dispatcher
  ports:
    - name: http
      port: 8080
---
# This ReplicaSet runs function storage. Note that the number of replicates
# must be exactly 1. The function-storage-agent is not designed to be
# replicated.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: storage
  namespace: containerless
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: storage
        image: localhost:32000/function-storage
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: containerless
  labels:
    app: storage
spec:
  type: NodePort
  selector:
    app: storage
  ports:
    - name: http
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: containerless-ingress
  namespace: containerless
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
        - path: /storage(/|$)(.*)
          pathType: Exact
          backend:
            service:
              name: storage
              port:
                name: http
        - path: /dispatcher(/|$)(.*)
          pathType: Exact
          backend:
            service:
              name: dispatcher
              port:
                name: http
        - path: /controller(/|$)(.*)
          pathType: Exact
          backend:
            service:
              name: controller
              port:
                name: http
---
# This pod echos the controller's log file to its own standard output, so that
# it appears in the Kubernetes log.
apiVersion: v1
kind: Pod
metadata:
  name: controller-logger
  namespace: containerless
spec:
  containers:
  - name: controller-logger
    image: localhost:32000/controller-logger
    volumeMounts:
      - name: log
        mountPath: "/log"
  volumes:
    - name: log
      hostPath:
        path: $CONTROLLER_LOG_PATH
  terminationGracePeriodSeconds: 1    
