# Namespace for Containerless
apiVersion: v1
kind: Namespace
metadata:
    name: containerless
---
apiVersion: v1
kind: Endpoints
metadata:
  name: controller
  namespace: containerless
subsets:
  - addresses:
    - ip: $CONTROLLER_IP
    ports:
    - port: $CONTROLLER_PORT
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: containerless
  labels:
    app: controller
spec:
  ports:
    - name: http
      port: 80
      targetPort: $CONTROLLER_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcher
  namespace: containerless
  labels:
    app: dispatcher
spec:
  type: NodePort
  selector:
    app: dispatcher
  ports:
    - name: http
      port: 8080
---
# This ReplicaSet runs function storage. Note that the number of replicates
# must be exactly 1. The function-storage-agent is not designed to be
# replicated.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: storage
  namespace: containerless
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: storage
        image: localhost:32000/function-storage
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: storage
            mountPath: "/storage"
      volumes:
        - name: storage
          hostPath:
            path: $EXAMPLES_PATH
---
apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: containerless
  labels:
    app: storage
spec:
  type: NodePort
  selector:
    app: storage
  ports:
    - name: http
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: containerless-ingress
  namespace: containerless
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
        - path: /storage(/|$)(.*)
          pathType: Exact
          backend:
            service:
              name: storage
              port:
                name: http
        - path: /dispatcher(/|$)(.*)
          pathType: Exact
          backend:
            service:
              name: dispatcher
              port:
                name: http
        - path: /controller(/|$)(.*)
          pathType: Exact
          backend:
            service:
              name: controller
              port:
                name: http
---
# This pod echos the controller's log file to its own standard output, so that
# it appears in the Kubernetes log.
apiVersion: v1
kind: Pod
metadata:
  name: controller-logger
  namespace: containerless
spec:
  containers:
  - name: controller-logger
    image: localhost:32000/controller-logger
    volumeMounts:
      - name: log
        mountPath: "/log"
  volumes:
    - name: log
      hostPath:
        path: $CONTROLLER_LOG_PATH
  terminationGracePeriodSeconds: 1    
