all:
	cd dispatcher && make
	cd function-runner && make
	cd function-storage && make
	cd controller-logger && make
	cd local-database && make

release:
	cd dispatcher && make release
	cd function-runner && make release
	cd function-storage && make release
	cd controller-logger && make release
	cd local-database && make release
