[workspace]
members = [
    "shared",
    "controller-agent",
    "dispatcher-agent",
    "dispatcher-launcher-agent",
    "function-runner-agent",
    "function-storage-agent",
    "k8s",
    "integration-tests",
    "dispatcher-agent-lib",
    "cli",
    "benchmarks"
]
exclude = [ "local" ]