name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    #- name: Clean
    #  run: cargo clean
    #  working-directory: ./containerless/rust
    - name: Install microk8s
      run: sudo snap install microk8s --classic
    - name: Allow runner to access microk8s
      run: |
        sudo chmod 777 /var/snap/microk8s/current/credentials/
        sudo chmod 666 /var/snap/microk8s/current/credentials/client.config
        sudo chmod 777 /var/snap/microk8s/current/args/
        sudo chmod 666 /var/snap/microk8s/current/args/kubectl
    #sudo usermod -a -G microk8s runner
    #sudo chown -f -R runner ~/.kube
    - name: Enable stuff on microk8s
      run: microk8s.enable dns registry ingress
    - name: Move the Kubeconfig
      run: sudo microk8s.kubectl config view > ~/.kube/config
    - name: Build Containerless
      run: ./build.sh
      working-directory: ./containerless
    - name: Test javascript/containerless/
      run: yarn run test
      working-directory: ./containerless/javascript/containerless
    - name: Check microk8s.kubectl status
      run: |
        sleep 10
        microk8s.kubectl get pods -n containerless --kubeconfig ~/.kube/config
    - name: Deploy Containerless
      run: ./deploy.sh
      working-directory: ./.github/workflows
    - name: Check microk8s.kubectl status
      run: |
        sleep 10
        microk8s.kubectl get pods -n containerless --kubeconfig ~/.kube/config
    - name: Run integration tests
      run: ./test.sh
      working-directory: ./containerless
    - name: Undeploy Containerless
      if: always()
      run: ./undeploy.sh
      working-directory: ./.github/workflows