name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Clean
      run: cargo clean
      working-directory: ./containerless/rust
    - name: Build
      run: ./build.sh
      working-directory: ./containerless
    - name: Test javascript/containerless/
      run: yarn run test
      working-directory: ./containerless/javascript/containerless
    - name: Check status
      run: |
        sleep 10
        microk8s.kubectl get pods -n containerless
    - name: Deploy
      run: ./deploy.sh
      working-directory: ./containerless
    - name: Check status
      run: |
        sleep 10
        microk8s.kubectl get pods -n containerless
    - name: Run integration tests
      run: ./test.sh
      working-directory: ./containerless/docker
    - name: Undeploy
      if: always()
      run: ./undeploy.sh
      working-directory: ./containerless