name: CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    #- name: Clean
    #  run: cargo clean
    #  working-directory: ./containerless/rust
    - name: Build
      run: ./build.sh
      working-directory: ./containerless
    - name: Test javascript/containerless/
      run: yarn run test
      working-directory: ./containerless/javascript/containerless
    - name: Check k8s status (should be empty)
      run: |
        microk8s.kubectl get all -n containerless
    - name: Deploy
      run: ./deploy.sh
      working-directory: ./containerless
    - name: Check k8s
      run: |
        microk8s.kubectl get all -n containerless
    - name: Run integration tests
      run: ./test.sh
      working-directory: ./containerless
    - name: Undeploy
      if: always()
      run: ./undeploy.sh
      working-directory: ./containerless